merge branch lesson5 with branch master
JonDorian/JavaHomework pull request #1
Opened 2021-01-31 14:08 UTC by JonDorian

2021-01-31 14:16 UTC, yurachel commented on src/com/tms/lesson5/additional/Task7.java
> +    for (int i = 1; i < 100; i++) {
Как мне написал Рома,можно просто написать i+=2;

2021-01-31 15:17 UTC, JonDorian commented on src/com/tms/lesson5/additional/Task7.java
> +    for (int i = 1; i < 100; i++) {
Круто! Если по четным, и с нечетными тоже отлично (если изначально счетчик с 1цы). и не нужно лишнюю проверку тогда писать, а на прямую в условии) Спасибо!

2021-02-01 04:53 UTC, yurachel approved these changes

2021-02-03 16:55 UTC, RomanKashenok requested changes

2021-02-03 16:55 UTC, RomanKashenok commented on src/com/tms/lesson5/AmountBetweenMinAndMax.java
> +    for (int x = 1; x < array.length - 1; x++) {
this is not a solution. You just get sum of elements from SECOND to LAST (even here it's not a task result). You shouldn't sort an array - you need to find sum from lower to higher element, but not from first to last...

2021-02-03 16:55 UTC, RomanKashenok commented on src/com/tms/lesson5/Butterfly.java
> +    String[][] array = new String[9][9];
Why do you need String, if you putting only char?

2021-02-03 16:55 UTC, RomanKashenok commented on src/com/tms/lesson5/LargerRandomNumber.java
> +      for (int two = 0; two < array.length - 1 - one; two++) {
sorting is an unnecessary and extra operation. Look for a solution without sorting please

2021-02-03 16:55 UTC, RomanKashenok commented on src/com/tms/lesson5/MaximumAndMinimumScore.java
> +      for (int second = 0; second < scoreList.length - first - 1; second++) {
sorting is an unnecessary and extra operation. Look for a solution without sorting please.
and we need not only values of marks, but their indexes too.

2021-02-03 16:55 UTC, RomanKashenok commented on src/com/tms/lesson5/SimpleNumber.java
> +    for (int i = 2; i < number / 2; i++) {
iterations number could be reduced

2021-02-03 16:55 UTC, RomanKashenok commented on src/com/tms/lesson5/SumOfIntegers.java
> +      if (counter == 2) {
how can I find sum of first 3,4,5 ... numbers according to task? Set it with Scanner or Random plese.

2021-02-03 16:55 UTC, RomanKashenok commented on src/com/tms/lesson5/additional/Task1.java
> +        distance = (float) Math.ceil((distance + ((distance * 10) / 100)) * rounding) / rounding;
too complicated. distance += distance*1.1 - It looks easier

2021-02-03 16:55 UTC, RomanKashenok commented on src/com/tms/lesson5/additional/Task3.java
> +    for (int i = 0; i <= 8; i++) {
what means number 8? What if we need not 8, but 10? I think we need to set up not power of 2, but number to iterate to(256 in our case)

2021-02-03 16:55 UTC, RomanKashenok commented on src/com/tms/lesson5/additional/Task5.java
> +  public static void main(String[] args) {
we need to know how much inches in 5 santimeters, but not how it will be spelled

2021-02-04 14:55 UTC, yurachel commented on src/com/tms/lesson5/MaximumAndMinimumScore.java
> +    boolean firstPass = true;
А для чего тут булевая переменная?)Вроде можно было бы и без нее

2021-02-04 15:27 UTC, JonDorian commented on src/com/tms/lesson5/MaximumAndMinimumScore.java
> +    boolean firstPass = true;
Т.к у меня рандом от 0 начинается, и если в массиве встретится несколько нулей - то будет записан лишь первый)

2021-02-04 15:50 UTC, JonDorian commented on src/com/tms/lesson5/additional/Task3.java
> +    for (int i = 0; i <= 8; i++) {
Вычислить: 1+2+4+8+...+256 - я увидел в этом задании 8 байт, каждый из которых степень двойки)

2021-02-04 16:04 UTC, JonDorian commented on src/com/tms/lesson5/additional/Task5.java
> +  public static void main(String[] args) {
??? **Задание:** Напишите программу **печати таблицы** перевода расстояний из дюймов в сантиметры **для значений длин от 1 до 20 дюймов**. 1 дюйм = 2,54 см.

2021-02-04 16:07 UTC, JonDorian commented on src/com/tms/lesson5/AmountBetweenMinAndMax.java
> +    for (int x = 1; x < array.length - 1; x++) {
Исправил)

2021-02-04 16:07 UTC, JonDorian commented on src/com/tms/lesson5/Butterfly.java
> +    String[][] array = new String[9][9];
Исправил)

2021-02-04 16:08 UTC, JonDorian commented on src/com/tms/lesson5/LargerRandomNumber.java
> +      for (int two = 0; two < array.length - 1 - one; two++) {
Исправил)

2021-02-04 16:08 UTC, JonDorian commented on src/com/tms/lesson5/MaximumAndMinimumScore.java
> +      for (int second = 0; second < scoreList.length - first - 1; second++) {
Исправил)

2021-02-04 16:08 UTC, JonDorian commented on src/com/tms/lesson5/SimpleNumber.java
> +    for (int i = 2; i < number / 2; i++) {
Исправил)

2021-02-04 16:08 UTC, JonDorian commented on src/com/tms/lesson5/SumOfIntegers.java
> +      if (counter == 2) {
Исправил)

2021-02-04 16:09 UTC, JonDorian commented on src/com/tms/lesson5/additional/Task1.java
> +        distance = (float) Math.ceil((distance + ((distance * 10) / 100)) * rounding) / rounding;
Действительно!) выглядит жестко)

2021-02-06 14:55 UTC, RomanKashenok requested changes

2021-02-06 14:55 UTC, RomanKashenok commented on src/com/tms/lesson5/SumOfIntegers.java
> +    for (int i = randomNumber; i < 50; i++) {
откуда здесь это?
мне надо найти сумму перых 5 чисел, что делятся на 3 - это 3, 6,9 12 и 15. Как я их здесь могу найти? Если рандомом выпадет 46? только 48 подойдёт?

2021-02-06 14:55 UTC, RomanKashenok commented on src/com/tms/lesson5/SumOfIntegers.java
> +      if (counter == 2) {
не вижу ))

2021-02-06 14:55 UTC, RomanKashenok commented on src/com/tms/lesson5/additional/Task5.java
> +  public static void main(String[] args) {
сорри прогнал... все ок тут"

2021-02-07 09:49 UTC, JonDorian commented on src/com/tms/lesson5/SumOfIntegers.java
> +    for (int i = randomNumber; i < 50; i++) {
Исправил)

2021-02-07 15:26 UTC, RomanKashenok requested changes

2021-02-07 15:26 UTC, RomanKashenok commented on src/com/tms/lesson5/SumOfIntegers.java
> +    for (int i = randomNumber; i < (randomNumber + 15); i++) {
what if I need to count sum of first 100/1000/10000 numbers that divides by 3 ? 
write universal solution for any possible case

2021-02-07 15:29 UTC, RomanKashenok commented on src/com/tms/lesson5/additional/Task3.java
> +    for (int i = 0; i <= 8; i++) {
чиво? Я говрю, что тут должна быть сумма чисел 1+2+4+8+16+32+64+128+256 - это уже 9 чисел. А если в условии будет стоять не 256, а 512 или 1024 или 2048 ну или т.д. ? Нужно универсальное решение. А 8 - вообще в условии нет нигде

2021-02-07 21:04 UTC, JonDorian commented on src/com/tms/lesson5/SumOfIntegers.java
> +    for (int i = randomNumber; i < (randomNumber + 15); i++) {
Готово) теперь универсально) сори - до упору не понимал суть задания а перечитав его еще несколько раз - допер **найти сумму первых ****n**** целых** N!!!! Карл!!!!)))

2021-02-12 09:46 UTC, RomanKashenok approved these changes
мержи. я уже в коммитах запутался :)

2021-02-12 09:46 UTC, RomanKashenok commented on src/com/tms/lesson5/SumOfIntegers.java
> +    for (int i = randomNumber; i < (randomNumber + 15); i++) {
Да как универсально-то... что вот это такое: randomNumber + 15. ЧТо такое randomNumber в прицнипе? Я вот поставил вместо него число 3, ожидая получить на выходе 3 + 6 + 9 = 18. получаю это вот: 
Число 3 делится на 3
Число 6 делится на 3
Число 9 делится на 3
Число 12 делится на 3
Число 15 делится на 3
Сумма 5ти первых целых чисел делящихся на 3 равна: 45

откуда 5 чисел? 

решение же проще некуда вообще:
        int howMuchNumbersDoYouNeed = 5;
        int sum = 0;
        for (int i = 0; i <= howMuchNumbersDoYouNeed*3; i+=3) {
            sum+=i;
        }
        System.out.println(sum);
    }

2021-02-12 12:26 UTC, JonDorian commented on src/com/tms/lesson5/SumOfIntegers.java
> +    for (int i = randomNumber; i < (randomNumber + 15); i++) {
спасибо за подсказку в решении) а ведь действительно простое решение) в **последнем** коммите по этому заданию все уже было универсально)))

2021-02-12 17:31 UTC, merged