merge branch Lesson6 with branch master (added task's 18-23 and TicTacToe game)
JonDorian/JavaHomework pull request #2
Opened 2021-02-07 09:03 UTC by JonDorian

2021-02-07 09:58 UTC, yurachel approved these changes

2021-02-07 15:43 UTC, RomanKashenok requested changes

2021-02-07 15:43 UTC, RomanKashenok commented on src/com/tms/lesson6/LastLetters.java
> +          } else if (symbol == ' ' || symbol == '-' || symbol == '.' || symbol == '?' || symbol == '!') {
we have classes for work with String - Pattern - Matcher and StringTokenizer. Use them please (in your case logic works only for your sentence)

2021-02-07 15:43 UTC, RomanKashenok commented on src/com/tms/lesson6/ParagraphSearch.java
> +    text = text.replaceAll("<p(\\s(id)?\\s?=\\s?\\W\\S+\\W)?>", "<p>");
paragraph tag has much more possible attributes than only id (class, style, align and ctr.). Your logic will work with only id attribute. Rewrite please

2021-02-07 15:43 UTC, RomanKashenok commented on src/com/tms/lesson6/PunctuationMarks.java
> +      if (symbol == ',' || symbol == '-' || symbol == '.' || symbol == '?') {
you forgot about :;-!() and ctr. For that purpose regexp has special group (puncht if I'm right - you can google it)

2021-02-07 15:43 UTC, RomanKashenok commented on src/com/tms/lesson6/WordsInText.java
> +    for (int i = 0; i < text.length(); i++) {
Use special classes for that (Pattern-Matcher, StringTokenizer)

2021-02-07 22:14 UTC, JonDorian commented on src/com/tms/lesson6/LastLetters.java
> +          } else if (symbol == ' ' || symbol == '-' || symbol == '.' || symbol == '?' || symbol == '!') {
Поправил) да знаю, знаю что такие есть) в момент когда делал все это - еще не смотрел видео нашего урока, а по методичке задания делал по ходу пройденного в ней - и до этих заданий а именно (18, 19, 20) ни слова не было про Pattern и Matcher, по этому делал основываясь на том, что зал и как сумел)

2021-02-07 22:23 UTC, JonDorian commented on src/com/tms/lesson6/WordsInText.java
> +    for (int i = 0; i < text.length(); i++) {
Исправил)

2021-02-07 23:16 UTC, JonDorian commented on src/com/tms/lesson6/PunctuationMarks.java
> +      if (symbol == ',' || symbol == '-' || symbol == '.' || symbol == '?') {
Исправил) за puncht - отдельное спасибо!)

2021-02-07 23:29 UTC, JonDorian commented on src/com/tms/lesson6/ParagraphSearch.java
> +    text = text.replaceAll("<p(\\s(id)?\\s?=\\s?\\W\\S+\\W)?>", "<p>");
Поправил) теперь работает как с id так и без него (на случай кастомных тегов или прочей шляпы) а в случае с id - проверит его написание на косяк)

2021-02-10 21:32 UTC, ArturSidelnikovs approved these changes

2021-02-13 14:44 UTC, RomanKashenok approved these changes
моженшь мержить

2021-02-13 14:44 UTC, RomanKashenok commented on src/com/tms/lesson6/PunctuationMarks.java
> +    System.out.print("Общее колличество знаков припинания: " + sumOfPunctuationMarks);
Будем считать что он. Но вообще я хотел что бы ты нашел вот такой паттерн: {Punct}

2021-02-13 19:37 UTC, merged