merge branch lesson10 with branch master
JonDorian/JavaHomework pull request #3
Opened 2021-02-17 16:56 UTC by JonDorian

Task's 24-27, aditional task's: "Transport", "Robot", "Human", "Spaceport"

2021-02-18 05:27 UTC, yurachel approved these changes

2021-02-20 15:23 UTC, RomanKashenok requested changes

2021-02-20 15:23 UTC, RomanKashenok commented on src/com/tms/lesson10/aditionals/human/HumanRunner.java
> +    Parka parka = new Parka();
лучше по типу интерфейса создавать - тогда их можно будет сгруппировать

2021-02-20 15:23 UTC, RomanKashenok commented on src/com/tms/lesson10/aditionals/robot/Run.java
> +    SamsungHead samsungHead = new SamsungHead(70);
опять же - лучше создавать по типу интерфейса

2021-02-20 15:23 UTC, RomanKashenok commented on src/com/tms/lesson10/aditionals/spacex/Spaceport.java
> +    Starship starship = new Starship();
сделай по типу интерфейса

2021-02-20 15:23 UTC, RomanKashenok commented on src/com/tms/lesson10/aditionals/transport/Air.java
> +public abstract class Air extends Transport {
Воздух расширяет Транспорт? :)

2021-02-20 15:23 UTC, RomanKashenok commented on src/com/tms/lesson10/task25/ATM.java
> +  public void addMoney(int par) {
странный метод для банкомата )))

2021-02-20 15:23 UTC, RomanKashenok commented on src/com/tms/lesson10/task25/ATM.java
> +  public boolean cashWithdrawal(int withdrawalAmount) {
Больно сложный метод - не осилил его весь :) Но вроде работать должно

2021-02-20 15:23 UTC, RomanKashenok commented on src/com/tms/lesson10/task26/Appliances.java
> +  boolean turnOnOrOf = false;
лучше что-то одно выбрать в имени включеноИлиВыключено = ложь;

2021-02-20 15:23 UTC, RomanKashenok commented on src/com/tms/lesson10/task26/SomeTV.java
> +public class SomeTV extends TV {
Если класс extends от другого, то надо бы что бы он как-то его расширял. А у тебя никакой разницы между SomeTV и TV по сути нет

2021-02-20 15:23 UTC, RomanKashenok commented on src/com/tms/lesson10/task26/SomeWashingMachine.java
> +public class SomeWashingMachine extends WashingMachines {
тож самое

2021-02-20 15:23 UTC, RomanKashenok commented on src/com/tms/lesson10/task27/CorporateCards.java
> +public abstract class CorporateCards extends CreditCards {
Как и с бытовой техникой

2021-02-26 17:49 UTC, RomanKashenok approved these changes

2021-02-27 21:04 UTC, merged